/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import org.sharing.FileController;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        try {
            FileController fc = new FileController(4000);
            fc.startServer();
        } catch (Exception ex) {
            System.out.println("Exception occurred. " + ex.getMessage());
        }
    }
}
